#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */
 
  enum userspace_layers {
    _QWERTY  = 0,
    _COLEMAK,
    _NUM,
    _SYM,
    _COMMAND,
    _NUMPAD,
    _MOVE,
    _SWITCH
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	// qwerty
	[_QWERTY] = LAYOUT( \
	//,-----------------------------------------------------.                    ,-----------------------------------------------------.
	LT(5,KC_TAB), 	KC_Q, 	KC_W, 	KC_E, 	KC_R, 	KC_T, 							LT(7,KC_Y), KC_U, 	KC_I, 	 KC_O, 	 KC_P, 	KC_BSPC,      \
	//|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
	KC_LCTL, 		KC_A, 	KC_S, 	KC_D, 	KC_F, 	KC_G, 							KC_H, 	  KC_J, 	KC_K, 	 KC_L, LT(5,KC_SCLN), KC_QUOT,\
	//|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
	KC_LSFT, 		KC_Z, 	KC_X, 	KC_C, 	KC_V, 	KC_B, 							KC_N, 	  KC_M, KC_COMM,  KC_DOT, KC_SLSH, KC_RSFT,       \
    //|--------+--------+--------+--------+--------+--------+--------|  |--------+--------+--------+--------+--------+--------+--------|
										 KC_LGUI,   MO(2),  KC_SPC, 	KC_ENT,    MO(3), KC_RALT  \
									   //`--------------------------'  `--------------------------'
	),
	
	// colemak 
	[_COLEMAK] = LAYOUT( \
	//,-----------------------------------------------------.                    ,-----------------------------------------------------.
	    KC_TRNS, 	KC_Q, 	 KC_W, 	  KC_F,    KC_P,    KC_G, 					LT(7,KC_J),    KC_L,    KC_U,    KC_Y, KC_SCLN, KC_TRNS,  \
	//|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
	    KC_TRNS,    KC_A,    KC_R,    KC_S,    KC_T,    KC_D, 						  KC_H,    KC_N,    KC_E,    KC_I,LT(5,KC_O),KC_TRNS, \
	//|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|		
		KC_TRNS,    KC_Z,    KC_X,    KC_C,    KC_V, KC_TRNS, 						  KC_K,    KC_M, KC_COMM,  KC_DOT, KC_SLSH, KC_TRNS,  \
	//|--------+--------+--------+--------+--------+--------+--------|  |--------+--------+--------+--------+--------+--------+--------|
		                                   KC_TRNS, KC_TRNS, KC_TRNS,     KC_TRNS, KC_TRNS, KC_TRNS \
										//`--------------------------'  `--------------------------'
	),
										   
										   
	// numbers
	[_NUM] = LAYOUT( \
	//,-----------------------------------------------------.                    ,-----------------------------------------------------.
	     KC_ESC,    KC_1,    KC_2,    KC_3,    KC_4,    KC_5, 					      KC_6,    KC_7,    KC_8,    KC_9,    KC_0, KC_BSPC,  \
	//|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
	    KC_LCTL,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO, 					   KC_LEFT, KC_DOWN,   KC_UP, KC_RGHT,   KC_NO,  KC_DEL,  \
	//|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
		KC_LSFT,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,					     KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,  \
	//|--------+--------+--------+--------+--------+--------+--------|  |--------+--------+--------+--------+--------+--------+--------|
											KC_LGUI, KC_TRNS,  KC_SPC,     KC_ENT,   MO(4), KC_RALT  \
										//`--------------------------'  `--------------------------'
	),
	
	// symbols
	[_SYM] = LAYOUT( \
	//,-----------------------------------------------------.                    ,-----------------------------------------------------.
	     KC_ESC, KC_EXLM,   KC_AT, KC_HASH,  KC_DLR, KC_PERC, 					   KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_BSPC, \
    //|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
	    KC_LCTL,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO, 					   KC_MINS,  KC_EQL, KC_LCBR, KC_RCBR, KC_PIPE, KC_GRV,  \
	//|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
		KC_LSFT,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO, 					   KC_UNDS, KC_PLUS, KC_LBRC, KC_RBRC, KC_BSLS, KC_TILD, \
	//|--------+--------+--------+--------+--------+--------+--------|  |--------+--------+--------+--------+--------+--------+--------|
											KC_LGUI,   MO(4),  KC_SPC,     KC_ENT, KC_TRNS, KC_RALT    \
										//`--------------------------'  `--------------------------'
	),
	
	// commands 
	[_COMMAND] = LAYOUT( \
	//,-----------------------------------------------------.                    ,-----------------------------------------------------.
	      RESET,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO, 						 KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO, \
    //|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
	    RGB_TOG, RGB_HUI, RGB_SAI, RGB_VAI,   KC_NO,   TO(0), 						 KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO, \
	//|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
		RGB_MOD, RGB_HUD, RGB_SAD, RGB_VAD,   KC_NO,   TO(1), 					     KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO, \
	//|--------+--------+--------+--------+--------+--------+--------|  |--------+--------+--------+--------+--------+--------+--------|
										    KC_LGUI, KC_TRNS,  KC_SPC,     KC_ENT, KC_TRNS, KC_RALT  \
										//`--------------------------'  `--------------------------'
	),
	
	// numpad 
	[_NUMPAD] = LAYOUT( \
	//,-----------------------------------------------------.                    ,-----------------------------------------------------.
	LT(0,KC_NO),   KC_NO,   KC_NO,   KC_NO,   KC_NO, KC_NO, 					     KC_P7,   KC_P8,   KC_P9,   KC_NO,   KC_NO, KC_BSPC, \
	//|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
	      KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO, 						 KC_P4,   KC_P5,   KC_P6,   KC_NO,   KC_NO,   KC_NO, \
	//|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|	  
		  KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO, 						 KC_P1,   KC_P2,   KC_P3,   KC_NO,   KC_NO,   KC_NO, \
	//|--------+--------+--------+--------+--------+--------+--------|  |--------+--------+--------+--------+--------+--------+--------|		  
											  OSM(MOD_MEH),   KC_NO,   KC_NO,     KC_ENT,   KC_P0,  KC_PDOT \
										//`--------------------------'  `--------------------------'
	),	  
		  
	// amovement 
	[_MOVE] = LAYOUT( \
	//,-----------------------------------------------------.                    ,-----------------------------------------------------.
	LT(0,KC_NO),   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO, 					   KC_HOME,  KC_UP,  KC_PGUP,   KC_NO,   KC_NO,   KC_NO, \
	//|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
	      KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO, 					   KC_LEFT,  KC_ENT, KC_RGHT,   KC_NO,   KC_NO,   KC_NO, \
	//|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|	  		 
		 KC_APP,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO, 						KC_END, KC_DOWN, KC_PGDN,  KC_DEL,   KC_NO,   KC_NO, \
	//|--------+--------+--------+--------+--------+--------+--------|  |--------+--------+--------+--------+--------+--------+--------|		  
		                                      KC_NO,   KC_NO,   KC_NO,    KC_TRNS,   KC_NO,   KC_NO  \
										//`--------------------------'  `--------------------------'
											),
	// layer switcher 
	[_SWITCH] = LAYOUT(\
	//,-----------------------------------------------------.                    ,-----------------------------------------------------.
	      TO(0),   TO(1),   TO(2),   TO(3),   TO(4),   TO(5), 					     TO(6),   TO(7),   KC_NO,   KC_NO,   KC_NO,   RESET,  \
	//|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
	      KC_NO,   KC_NO, KC_BRIU,   KC_NO,   KC_NO,   KC_NO, 						 KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO, EEP_RST, \
	//|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
		KC_SLEP,   KC_NO, KC_BRID,   KC_NO,   KC_NO,   KC_NO, 						 KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO, \
	//|--------+--------+--------+--------+--------+--------+--------|  |--------+--------+--------+--------+--------+--------+--------|		  		
											  KC_NO,   KC_NO,   KC_NO,      KC_NO,   KC_NO,   KC_NO  \
										//`--------------------------'  `--------------------------'
	
	)
};


// it appears that these are different to the board numbering. 
// when you specify n here, it lightss up n+1 on the board diagram - actually may be an entirely different pattern 

// _COLEMAK,
// Light on inner column and underglow 
const rgblight_segment_t PROGMEM layer_colemak_lights[] = RGBLIGHT_LAYER_SEGMENTS(
    {0, 10, HSV_RED}
);

// _NUM,
// Light on inner column and underglow 
const rgblight_segment_t PROGMEM layer_num_lights[] = RGBLIGHT_LAYER_SEGMENTS(
    {0, 10, HSV_TEAL}
);
// _SYMBOL,
// Light on inner column and underglow 
const rgblight_segment_t PROGMEM layer_symbol_lights[] = RGBLIGHT_LAYER_SEGMENTS(
    {0, 10, HSV_BLUE}
);
// _COMMAND,
// Light on inner column and underglow 
const rgblight_segment_t PROGMEM layer_command_lights[] = RGBLIGHT_LAYER_SEGMENTS(
    {0, 10, HSV_PURPLE}
);


//_NUMPAD
//havent worked out how to do each side individually either 
const rgblight_segment_t PROGMEM layer_numpad_lights[] = RGBLIGHT_LAYER_SEGMENTS(
{0, 10, HSV_ORANGE}
);
const rgblight_segment_t PROGMEM layer_numpad_rh_lights[] = RGBLIGHT_LAYER_SEGMENTS(
	{0, 13, HSV_ORANGE},
    {15, 3, HSV_ORANGE}
);

// _MOVE,
// Light on inner column and underglow 
const rgblight_segment_t PROGMEM layer_move_lights[] = RGBLIGHT_LAYER_SEGMENTS(
    {0, 10, HSV_PINK}
);

// _SWITCHER   // light up top row
const rgblight_segment_t PROGMEM layer_switcher_lights[] = RGBLIGHT_LAYER_SEGMENTS( 
    {0, 6, HSV_GREEN},
	{9, 2, HSV_GREEN},
	{17, 2, HSV_GREEN},
	{23, 2, HSV_GREEN}
);


// Now define the array of layers. Later layers take precedence
const rgblight_segment_t* const PROGMEM my_rgb_layers[] = RGBLIGHT_LAYERS_LIST(
    layer_colemak_lights, 
	layer_num_lights,// overrides layer 1
	layer_symbol_lights,
    layer_command_lights,       
	layer_numpad_lights, 
	layer_numpad_rh_lights,
	layer_move_lights,
	layer_switcher_lights  // Overrides other layers
);

void keyboard_post_init_user(void) {
    // Enable the LED layers
    rgblight_layers = my_rgb_layers;
	rgblight_mode(10);// haven't found a way to set this in a more useful way 

}

void matrix_scan_user(void) {
	
  //rgblight_set_layer_state(0, layer_state_cmp(default_layer_state, _COLEMAK));
  //rgblight_set_layer_state(0, layer_state_cmp(default_layer_state, 1));
}


layer_state_t layer_state_set_user(layer_state_t state) {
    // Both layers will light up if both kb layers are active
	/*
	switch (get_highest_layer(state)) {
		case 1: // colemak 
			//rgblight_setrgb (0xFF,  0x00, 0x00);
			rgblight_set_layer_state(0, 1);
			break;
		case 4: // commands 
			//rgblight_setrgb (0x00,  0x00, 0xff);
			rgblight_set_layer_state(1, 1);
			break;	
		case 5: // numpad 
			//rgblight_setrgb (0x00,  0x00, 0xff);
			rgblight_set_layer_state(2, 1);
			break;	
		case 7: // switcher  
			//rgblight_setrgb (0x00,  0xFF, 0x00);
			rgblight_set_layer_state(3, 1);
			break;	
		default:
			break;
	}				
	*/
	//rgblight_setrgb (0x00,  0x00, 0xFF);
	// these work, but don't persist 
	rgblight_set_layer_state(0, layer_state_cmp(state, _COLEMAK));//layer_state_cmp(state, 1));
	rgblight_set_layer_state(1, layer_state_cmp(state, _NUM));
	rgblight_set_layer_state(2, layer_state_cmp(state, _SYM));
	rgblight_set_layer_state(3, layer_state_cmp(state, _COMMAND));
	rgblight_set_layer_state(4, layer_state_cmp(state, _NUMPAD));
	if (!has_usb())
		rgblight_set_layer_state(5, layer_state_cmp(state, _NUMPAD));
	rgblight_set_layer_state(6, layer_state_cmp(state, _MOVE));
	rgblight_set_layer_state(7, layer_state_cmp(state, _SWITCH));
    return state;
}

/*
bool led_update_user(led_t led_state) {
    rgblight_set_layer_state(0, led_state.caps_lock);
    return true;
}
*/
